server:
  ssl:
    key-store: classpath:digixo.jks
    key-store-password: 123456
    key-store-type: JKS
    key-alias: digixo
    key-password: 123456
  port: 8443

logging:
  level:
    org:
      springframework:
        jdbc:
          core: trace
        security: trace