server:
  ssl:
    key-store: classpath:digixo.jks
    key-store-password: 123456
    key-store-type: JKS
    key-alias: digixo
    key-password: 123456
  port: 8443



#server
#  ssl:
#    key-store-type: PKCS12
#    key-store: classpath:keystore/edge.p12
#    key-store-password: password
#    key-alias: localhost
#  port: 8443


#spring:
#  datasource:
#    username: root
#    password: 1234
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/springsecurityshod


#  security:
#    user:
logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE
        security: trace



authorization:
  key: test1234